version: '3.8'
services:
  backend:
    build:
      context: ../../part 1/Exercise 1.14/backend/  
      dockerfile: dockerfile 
    ports:
      - "8080:8080"
    
  frontend:
    build: 
      context: ../../part 1/Exercise 1.14/frontend/
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    