version: '3.8'
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  frontend:
    build: 
      context: ../../part 1/Exercise 1.14/frontend/
      dockerfile: dockerfile
    ports:
      - "3000:3000"
  redis:
      image: redis
      ports:
        - "6379:6379"
  backend:
    build:
      context: ../../part 1/Exercise 1.14/backend/  
      dockerfile: dockerfile 
    
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - REQUEST_ORIGIN=http://localhost/
    depends_on:
      - redis
      - postgres
  